// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ogxtdbkovocuxhgobchp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9neHRkYmtvdm9jdXhoZ29iY2hwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODYzMTYsImV4cCI6MjA2NTQ2MjMxNn0.d07_dzw18aOkha4aXqaM1thewTjJ0Dy4tqoMeMhgEs0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);